/** Zentrale UI-Texte. Neue Texte hier ergänzen, nicht im Komponenten-Code verstreuen. */
export const texte = {
  appName: 'Netzwerkstatt',
  untertitel: 'Netzwerk-Simulator für den Informatikunterricht',
  stufeWaehlen: 'Klassenstufe',
  modusAufbauen: 'Aufbauen',
  modusAusprobieren: 'Ausprobieren',
  modusWaehlen: 'Modus',
  leereArbeitsflaeche:
    'Tippe links auf ein Gerät, um es hier abzulegen. Verbinde Geräte, indem du vom Punkt an einem Gerät zu einem anderen ziehst oder tippst.',
  arbeitsflaeche: 'Arbeitsfläche Netzplan',
  bausteine: 'Bausteine',
  endgeraete: 'Endgeräte',
  verteiler: 'Verteiler',
  verbindungsart: 'Verbindung',
  geraetHinzufuegen: (name: string) => `${name} hinzufügen`,
  datei: 'Datei',
  neu: 'Neu',
  oeffnen: 'Öffnen',
  speichern: 'Speichern',
  rueckgaengig: 'Rückgängig',
  wiederholen: 'Wiederholen',
  eigenschaften: 'Eigenschaften',
  name: 'Name',
  geraetetyp: 'Gerätetyp',
  leitungen: 'Leitungen',
  keineLeitungen: 'Noch nicht verbunden.',
  verbindenMit: 'Verbinden mit',
  verbindenPer: 'per',
  verbinden: 'Verbinden',
  bitteWaehlen: 'Gerät wählen …',
  entfernen: 'Entfernen',
  geraetEntfernen: 'Gerät entfernen',
  leitungEntfernen: 'Leitung entfernen',
  leitungZwischen: (a: string, b: string) => `${a} ↔ ${b}`,
  anschlussPunkt: (name: string) => `Anschluss von ${name}: hier ziehen oder tippen, um zu verbinden`,
  auswahlAufheben: 'Auswahl aufheben',
  ipAdresse: 'IP-Adresse',
  subnetzmaske: 'Subnetzmaske',
  gateway: 'Gateway',
  ipBeispiel: 'z. B. 192.168.0.10',
  ipVorschlag: 'Vorschlag',
  ipVorschlagBeschreibung: 'Nächste freie IP-Adresse im lokalen Rechnernetz eintragen',
  keineIp: 'keine IP',
  ipNichtNoetig: 'Switches und Access Points brauchen keine IP-Adresse – sie leiten Nachrichten nur weiter.',
  routerSpaeter:
    'Router verbinden verschiedene Netze. Ihre Einstellungen – eine IP-Adresse je Anschluss und die Routingtabelle – gibt es ab Klasse 11.',
  anschluesse: 'Anschlüsse',
  anschlussZu: (name: string) => `Anschluss zu ${name}`,
  keineAnschluesse: 'Der Router ist noch mit keinem Gerät verbunden.',
  anschlussVorschlag: (name: string) => `Freie IP-Adresse für den Anschluss zu ${name} eintragen`,
  gatewayVorschlagBeschreibung: 'IP-Adresse des Routers im eigenen lokalen Rechnernetz eintragen',
  privat: 'privat (lokal)',
  oeffentlich: 'öffentlich (global)',
  privatBeschreibung:
    'Private Adressen (10.x, 172.16–31.x, 192.168.x) gelten nur im lokalen Netz und kommen im Internet nicht vor.',
  oeffentlichBeschreibung: 'Öffentliche Adressen sind weltweit eindeutig und im Internet erreichbar.',
  routingtabelle: 'Routingtabelle',
  routingAutomatisch: 'automatisch',
  routingManuell: 'von Hand',
  routingModus: 'Routingtabelle wird',
  routingAutomatischHinweis:
    'Der Router berechnet seine Tabelle selbst: direkt angeschlossene Netze und für alle anderen den Weg über die wenigsten Router. Fällt eine Leitung aus, sucht er einen Umweg.',
  routingManuellHinweis: 'Die Tabelle gilt genau so, wie sie hier steht – auch wenn eine Leitung ausfällt.',
  routingUebernehmen: 'Automatische Tabelle übernehmen und von Hand bearbeiten',
  routingLeer: 'Keine Einträge. Ohne passenden Eintrag verwirft der Router Pakete.',
  zielnetz: 'Zielnetz',
  maskeKurz: 'Maske',
  ueber: 'Gateway',
  anschluss: 'Anschluss',
  metrik: 'Router bis Ziel',
  direkt: 'direkt',
  routeHinzufuegen: 'Route hinzufügen',
  routeEntfernen: (nr: number) => `Route ${nr} entfernen`,
  leitungAusgefallen: 'Leitung ausgefallen (Störung simulieren)',
  leitungAusgefallenHinweis:
    'Über eine ausgefallene Leitung geht nichts mehr. Router mit automatischer Tabelle suchen einen Umweg.',
  ausgefallen: 'ausgefallen',
  probleme: 'Probleme',
  nachrichtSenden: 'Nachricht senden',
  anIpAdresse: 'An IP-Adresse',
  nachrichtText: 'Text',
  nachrichtStandard: 'Hallo!',
  senden: 'Senden',
  eigeneIp: (ip: string) => `Eigene IP-Adresse: ${ip}`,
  ausprobierenHinweis:
    'Wähle ein Gerät aus und schicke eine Nachricht an eine IP-Adresse. Mit ⏭ verfolgst du sie Schritt für Schritt.',
  simulation: 'Simulation',
  abspielen: 'Abspielen',
  pause: 'Pause',
  einzelschritt: 'Einzelschritt',
  zuruecksetzen: 'Zurücksetzen',
  tempo: 'Tempo',
  zeitlupe: 'Zeitlupe',
  schnell: 'schnell',
  schrittNr: (n: number) => `Schritt ${n}`,
  angehalten: 'angehalten',
  protokoll: 'Protokoll',
  protokollZeigen: 'Protokoll anzeigen',
  protokollVerbergen: 'Protokoll verbergen',
  protokollLeer: 'Noch keine Nachrichten. Wähle ein Gerät und sende eine Nachricht.',
  spalteSchritt: 'Schritt',
  spalteStation: 'Station',
  spalteAn: 'an',
  spalteWas: 'Was passiert',
  paketNachricht: 'Nachricht',
  paketAntwort: 'Antwort',
  dnsServer: 'DNS-Server',
  dnsServerBeschreibung: 'IP-Adresse des DNS-Servers, den dieses Gerät nach Domains fragt',
  dnsVorschlagBeschreibung: 'IP-Adresse des DNS-Servers im lokalen Rechnernetz eintragen',
  dienste: 'Dienste',
  keineDienste: 'Auf diesem Gerät ist kein Dienst installiert.',
  installieren: (name: string) => `${name} installieren`,
  deinstallieren: (name: string) => `${name} entfernen`,
  dienstKlient: 'Client',
  dienstServer: 'Server-Dienst',
  seiten: 'Seiten',
  startseite: 'Startseite',
  seiteBearbeiten: (pfad: string) => `Seite ${pfad} bearbeiten`,
  bearbeiten: 'Bearbeiten',
  seiteHinzufuegen: 'Seite hinzufügen',
  seiteEntfernen: (pfad: string) => `Seite ${pfad} entfernen`,
  neueSeitePfad: (n: number) => `/seite${n}.html`,
  htmlEditorTitel: (pfad: string, geraet: string) => `Webseite ${pfad} auf ${geraet}`,
  htmlQuelltext: 'HTML-Quelltext',
  vorschau: 'Vorschau',
  pfad: 'Pfad (Adresse der Seite)',
  pfadHinweis: 'Beginnt mit „/“, z. B. /kontakt.html',
  pfadUngueltig:
    'Der Pfad muss mit „/“ beginnen, darf keine Leerzeichen enthalten und nicht doppelt vorkommen.',
  uebernehmen: 'Übernehmen',
  abbrechen: 'Abbrechen',
  dnsTabelle: 'Einträge (Domain → IP-Adresse)',
  dnsKeineEintraege: 'Noch keine Einträge. Ohne Eintrag kann der DNS-Server keine Domain auflösen.',
  domain: 'Domain',
  eintragHinzufuegen: 'Eintrag hinzufügen',
  eintragEntfernen: (domain: string) => `Eintrag ${domain || '(leer)'} entfernen`,
  domainBeispiel: 'www.schule.test',
  browserOeffnen: 'Browser öffnen',
  browser: 'Browser',
  browserVon: (geraet: string) => `Browser auf ${geraet}`,
  adresszeile: 'Adresse',
  aufrufen: 'Aufrufen',
  browserLeer: 'Gib oben eine Adresse ein, z. B. www.schule.test, und tippe auf „Aufrufen“.',
  browserDns: (domain: string, dns: string) =>
    `Frage den DNS-Server (${dns}) nach der IP-Adresse von ${domain} …`,
  browserLaden: (ip: string) => `Lade die Seite vom Webserver (${ip}) …`,
  seiteNichtGefunden: 'Seite nicht gefunden (404)',
  seiteNichtGefundenText: (pfad: string) =>
    `Der Webserver ist erreichbar, aber die Seite ${pfad} gibt es dort nicht. Prüfe den Pfad oder lege die Seite auf dem Webserver an.`,
  ansicht: 'Ansicht',
  hardware: (typ: string) => `Hardware: ${typ}`,
  ansichtInfrastruktur: 'Infrastruktur',
  ansichtDienste: 'Dienste',
  beispiele: 'Beispiele',
  beispieleTitel: 'Beispielnetze',
  beispieleEinleitung:
    'Fertige Netze zum Ausprobieren und Weiterbauen. Du kannst jedes Beispiel verändern und als eigene Datei speichern.',
  beispielOeffnen: (titel: string) => `${titel} öffnen`,
  oeffnenKurz: 'Öffnen',
  beispielErsetzen:
    'Das aktuelle Netz wird durch das Beispiel ersetzt. Nicht gespeicherte Änderungen gehen verloren. Fortfahren?',
  beispielGeoeffnet: (titel: string) => `Beispiel „${titel}“ geöffnet.`,
  oderBeispiel: 'Oder öffne ein fertiges Beispiel:',
  arbeitsauftrag: 'Arbeitsauftrag',
  auftragAusblenden: 'Arbeitsauftrag ausblenden',
  auftragEinblenden: 'Arbeitsauftrag',
  paketDetails: 'Details',
  paketDetailsZu: (was: string) => `Details zu ${was} anzeigen`,
  paketInspektorTitel: (was: string, von: string, an: string) => `${was}: ${von} → ${an}`,
  schichtenHinweis11:
    'Jede Schicht verpackt die Daten der Schicht darüber und fügt eigene Angaben hinzu. Klappe die Schichten von außen nach innen auf.',
  schichtenHinweis78:
    'Klappe auf, was in der Nachricht steckt: wohin sie geht (Infrastruktur) und was sie enthält (Dienst).',
  schichtNamen: {
    netzzugang: 'Netzzugangsschicht',
    vermittlung: 'Vermittlungsschicht',
    transport: 'Transportschicht',
    anwendung: 'Anwendungsschicht',
    infrastruktur: 'Infrastruktur – wohin?',
    dienst: 'Dienst – was?',
  },
  schichtAufgabe: {
    netzzugang: 'bringt das Paket zum nächsten Gerät auf diesem Abschnitt',
    vermittlung: 'findet den Weg durch die Netze bis zum Ziel',
    transport: 'liefert die Daten an das richtige Programm (Port)',
    anwendung: 'enthält das, was die Programme sich mitteilen',
  },
  untenAnsicht: 'Darstellung',
  sequenzdiagramm: 'Sequenzdiagramm',
  zwischenstationen: 'Zwischenstationen zeigen (Switches, Router)',
  sequenzLeer: 'Noch keine Kommunikation. Sende eine Nachricht oder rufe eine Webseite auf.',
  sequenzBeschreibung: (n: number, t: number) =>
    `Sequenzdiagramm mit ${n} Nachrichten zwischen ${t} Stationen`,
  alsSvgSpeichern: 'Als Bild (SVG) speichern',
  verloren: 'verloren',
  inPaketenSenden: 'In Paketen senden',
  zeichenProPaket: 'Zeichen pro Paket',
  langerText: 'Netzwerke verschicken Nachrichten in vielen kleinen Paketen.',
  empfangeneTeile: 'Empfangene Teile',
  gesendeteTeile: 'Gesendete Teile',
  teilFehlt: 'fehlt',
  ankunftReihenfolge: (liste: string) => `Reihenfolge der Ankunft: ${liste}`,
  zusammengesetzt: 'Zusammengesetzt',
  nochUnvollstaendig: 'noch unvollständig',
  bestaetigtVon: (b: number, n: number) => `${b} von ${n} Teilen bestätigt`,
  aufgegeben: 'aufgegeben',
  einstellungen: 'Einstellungen',
  mehrwege: 'Pakete dürfen verschiedene Wege nehmen',
  bestaetigen: 'Teile bestätigen und Fehlendes erneut senden (wie TCP)',
  startwert: 'Zufall',
  neuWuerfeln: (n: number) => `Neu würfeln (Durchlauf ${n})`,
  stoerung: 'Störung: Pakete gehen verloren',
  verlustProzent: (p: number) => (p === 0 ? 'keine' : `${p} %`),
  laufzeit: 'Laufzeit der Leitung',
  laufzeitText: (n: number) => (n === 1 ? 'normal (1 Schritt)' : `lang (${n} Schritte)`),
  verlustEtikett: (p: number) => `${p} % Verlust`,
  laufzeitEtikett: (n: number) => `${n} Schritte`,
  dhcpAutomatisch: 'IP-Adresse automatisch beziehen (DHCP)',
  dhcpHinweis:
    'IP-Adresse, Subnetzmaske, Gateway und DNS-Server bekommt dieses Gerät beim Ausprobieren von einem DHCP-Server.',
  dhcpHolen: 'IP-Adresse per DHCP holen',
  dhcpStatus: {
    suche: 'Sucht einen DHCP-Server …',
    anfrage: 'Fragt die angebotene Adresse an …',
    fertig: 'Adresse erhalten',
    fehler: 'Keine Adresse erhalten',
  },
  dhcpBereichVon: 'Adressen von',
  dhcpBereichBis: 'bis',
  natAnschluss: 'führt ins Internet (NAT)',
  natHinweis:
    'Pakete aus dem privaten Heimnetz bekommen an diesem Anschluss die öffentliche Adresse des Routers. Von außen ist das Heimnetz nicht direkt erreichbar.',
  natTabelle: 'NAT-Tabelle',
  natLeer: 'Noch keine Übersetzungen.',
  natInnen: 'Innen (privat)',
  natAussen: 'Außen (öffentlich)',
  natZiel: 'Ziel',
  nichtsAusgewaehlt: 'Wähle ein Gerät oder eine Leitung aus, um Details zu sehen und es zu bearbeiten.',
  offlineBereit: 'Die Netzwerkstatt funktioniert jetzt auch ohne Internet.',
  updateVerfuegbar: 'Eine neue Version ist verfügbar.',
  neuLaden: 'Neu laden',
  schliessen: 'Schließen',
} as const;

/** Deutsche Screenreader-Texte für die Netzplan-Bibliothek (React Flow). */
export const netzplanAriaTexte = {
  'node.a11yDescription.default':
    'Enter oder Leertaste wählt das Gerät aus. Entf entfernt es, Escape bricht ab.',
  'node.a11yDescription.keyboardDisabled':
    'Enter oder Leertaste wählt das Gerät aus. Danach verschieben es die Pfeiltasten. Entf entfernt es, Escape bricht ab.',
  'node.a11yDescription.ariaLiveMessage': ({
    direction,
    x,
    y,
  }: {
    direction: string;
    x: number;
    y: number;
  }) =>
    `Gerät nach ${({ up: 'oben', down: 'unten', left: 'links', right: 'rechts' } as Record<string, string>)[direction] ?? direction} verschoben, Position ${x}, ${y}`,
  'edge.a11yDescription.default':
    'Enter oder Leertaste wählt die Leitung aus. Entf entfernt sie, Escape bricht ab.',
  'controls.ariaLabel': 'Ansicht steuern',
  'controls.zoomIn.ariaLabel': 'Vergrößern',
  'controls.zoomOut.ariaLabel': 'Verkleinern',
  'controls.fitView.ariaLabel': 'Ganzes Netz anzeigen',
  'controls.interactive.ariaLabel': 'Bearbeiten sperren oder entsperren',
  'minimap.ariaLabel': 'Übersichtskarte',
  'handle.ariaLabel': 'Anschluss',
};
